#!/bin/bash

##
# Add a mount option to a mount-point in the fstab
# Use: add_mp_opt [mount point] [option]
add_mp_opt () {
    
    MP=$1
    OPTION=$2
    
    # If the mount-point is not there, return
    grep -qE ".*[ \t]+${MP}[ \t]+" /etc/fstab ||return 0

    # If it's already there return
    grep -qE ".*[ \t]+${MP}[ \t]+.*[,\t ]?${OPTION},?" /etc/fstab && return 0
    
    # add option
    sed -Ei "s|^([^ \t]+\s+)${MP}(\s+[^ \t]+)\s+([^ \t]+)(.*)|\1 ${MP}\2 \3\,${OPTION} \4|" /etc/fstab || return 1
    
    # remove defaults if necessary
    sed -Ei "s|(.*[ \t]+${MP}[ \t]+.*)defaults,?|\1|" /etc/fstab
 
    return 0
}

##
# Hard-set the entire mount options section for a given mount-point
set_mp_opts () {
    sed -Ei "s|^([^ \t]+\s+)${1}(\s+[^ \t]+)\s+[^ \t]+(.*)|\1 ${1}\2 ${2} \3|" /etc/fstab || return 1
}

##
# Set RH version and release information
set_rh_release () {

    if [ ! -f /etc/redhat-release ]; then
        echo "this does not appear to be a RHEL (or derivative) system, exiting"
        return 1
    fi

    if ! grep -qiE "centos|red hat|fedora" /etc/redhat-release; then
        cat << EOF
script may not support this OS:
    $(cat /etc/redhat-release),
exiting
EOF
        return 1
    fi
    
    export RH_VERSION=$(sed -E "s/.+release ([0-9]+)\.?([0-9]?) .+/\1/" /etc/redhat-release)
    export RH_RELEASE=$(sed -E "s/.+release [0-9]+\.([0-9]+) .+/\1/" /etc/redhat-release)
    export RH_TYPE=$(
        (grep -qi "fedora" /etc/redhat-release && echo "fedora")
        (grep -qi "centos" /etc/redhat-release && echo "el")
        (grep -qi "red hat" /etc/redhat-release && echo "el")
        (grep -qi "scientific" /etc/redhat-release && echo "el")
    )
    export RH_DIST=$(sed -E "s/(.+) release .*/\1/" /etc/redhat-release)
}


##
# The CIS bencmark renamed C2S for leagal reasons. Did I say CIS? No, I didn't.
C2S="ensure_redhat_gpgkey_installed \
package_aide_installed \
disable_prelink \
aide_build_database \
aide_periodic_cron_checking \
mount_option_nodev_nonroot_local_partitions \
mount_option_tmp_nodev \
mount_option_tmp_noexec \
mount_option_tmp_nosuid \
mount_option_dev_shm_nodev \
mount_option_dev_shm_noexec \
mount_option_dev_shm_nosuid \
mount_option_var_tmp_bind \
kernel_module_cramfs_disabled \
kernel_module_freevxfs_disabled \
kernel_module_jffs2_disabled \
kernel_module_hfs_disabled \
kernel_module_hfsplus_disabled \
kernel_module_squashfs_disabled \
kernel_module_udf_disabled \
userowner_shadow_file \
groupowner_shadow_file \
file_permissions_etc_shadow \
file_owner_etc_group \
file_groupowner_etc_group \
file_permissions_etc_group \
file_owner_etc_gshadow \
file_groupowner_etc_gshadow \
file_permissions_etc_gshadow \
file_owner_etc_passwd \
file_groupowner_etc_passwd \
file_permissions_etc_passwd \
file_permissions_binary_dirs \
sticky_world_writable_dirs \
umask_for_daemons \
disable_users_coredumps \
sysctl_fs_suid_dumpable \
sysctl_kernel_exec_shield \
sysctl_kernel_randomize_va_space \
enable_selinux_bootloader \
selinux_state \
selinux_policytype \
package_setroubleshoot_removed \
package_mcstrans_removed \
no_direct_root_logins \
accounts_no_uid_except_zero \
no_empty_passwords \
accounts_minimum_age_login_defs \
accounts_password_minlen_login_defs \
accounts_maximum_age_login_defs \
accounts_password_warn_age_login_defs \
account_disable_post_pw_expiration \
accounts_passwords_pam_faillock_deny \
accounts_password_pam_unix_remember \
set_password_hashing_algorithm_systemauth \
accounts_umask_bashrc \
accounts_umask_etc_profile \
file_user_owner_grub_conf \
file_group_owner_grub_conf \
file_permissions_grub_conf \
bootloader_password \
require_singleuser_auth \
disable_interactive_boot \
set_system_login_banner \
gconf_gdm_enable_warning_gui_banner \
gconf_gdm_set_login_banner_text \
sysctl_net_ipv4_conf_default_send_redirects \
sysctl_net_ipv4_conf_all_send_redirects \
sysctl_net_ipv4_conf_all_accept_source_route \
sysctl_net_ipv4_conf_all_accept_redirects \
sysctl_net_ipv4_conf_all_secure_redirects \
sysctl_net_ipv4_conf_all_log_martians \
sysctl_net_ipv4_conf_default_accept_source_route \
sysctl_net_ipv4_conf_default_accept_redirects \
sysctl_net_ipv4_conf_default_secure_redirects \
sysctl_net_ipv4_icmp_echo_ignore_broadcasts \
sysctl_net_ipv4_icmp_ignore_bogus_error_responses \
sysctl_net_ipv4_tcp_syncookies \
sysctl_net_ipv4_conf_all_rp_filter \
sysctl_net_ipv4_conf_default_rp_filter \
sysctl_net_ipv6_conf_default_accept_ra \
sysctl_net_ipv6_conf_default_accept_redirects \
service_ip6tables_enabled \
service_iptables_enabled \
kernel_module_dccp_disabled \
kernel_module_sctp_disabled \
kernel_module_rds_disabled \
kernel_module_tipc_disabled \
package_rsyslog_installed \
service_rsyslog_enabled \
rsyslog_send_messages_to_logserver \
ensure_logrotate_activated \
service_auditd_enabled \
bootloader_audit_argument \
auditd_data_retention_space_left_action \
auditd_data_retention_admin_space_left_action \
auditd_data_retention_action_mail_acct \
audit_rules_time_adjtimex \
audit_rules_time_settimeofday \
audit_rules_time_stime \
audit_rules_time_watch_localtime \
audit_rules_usergroup_modification \
audit_rules_networkconfig_modification \
audit_rules_mac_modification \
audit_rules_login_events \
audit_manual_session_edits \
audit_rules_unsuccessful_file_modification \
audit_rules_privileged_commands \
audit_rules_media_export \
audit_rules_file_deletion_events \
audit_rules_sysadmin_actions \
audit_rules_kernel_module_loading \
audit_rules_immutable \
uninstall_xinetd \
uninstall_telnet_server \
package_rsh-server_removed \
package_rsh_removed \
no_rsh_trust_files \
uninstall_ypserv \
package_ypbind_removed \
uninstall_tftp-server \
package_tftp_removed \
service_rhnsd_disabled \
service_crond_enabled \
service_atd_disabled \
sshd_allow_only_protocol2 \
sshd_set_idle_timeout \
sshd_disable_rhosts \
disable_host_auth \
sshd_disable_root_login \
sshd_disable_empty_passwords \
sshd_enable_warning_banner \
sshd_use_approved_ciphers \
packagegroup_xwindows_remove \
disable_avahi \
service_cups_disabled \
uninstall_dhcp_server \
service_ntpd_enabled \
ntpd_specify_remote_server \
package_openldap-servers_removed \
uninstall_vsftpd \
package_httpd_removed \
package_net-snmp_removed"

##
# United States Government Configuration Baseline. SCAP rules for that.
USGCB="ensure_redhat_gpgkey_installed \
security_patches_up_to_date \
package_aide_installed \
mount_option_nodev_nonroot_local_partitions \
mount_option_tmp_nodev \
mount_option_tmp_noexec \
mount_option_tmp_nosuid \
mount_option_dev_shm_nodev \
mount_option_dev_shm_noexec \
mount_option_dev_shm_nosuid \
mount_option_var_tmp_bind \
service_autofs_disabled \
kernel_module_cramfs_disabled \
kernel_module_freevxfs_disabled \
kernel_module_jffs2_disabled \
kernel_module_hfs_disabled \
kernel_module_hfsplus_disabled \
kernel_module_squashfs_disabled \
kernel_module_udf_disabled \
userowner_shadow_file \
groupowner_shadow_file \
file_permissions_etc_shadow \
file_owner_etc_group \
file_groupowner_etc_group \
file_permissions_etc_group \
file_owner_etc_gshadow \
file_groupowner_etc_gshadow \
file_permissions_etc_gshadow \
file_owner_etc_passwd \
file_groupowner_etc_passwd \
file_permissions_etc_passwd \
sticky_world_writable_dirs \
umask_for_daemons \
disable_users_coredumps \
sysctl_fs_suid_dumpable \
sysctl_kernel_exec_shield \
sysctl_kernel_randomize_va_space \
enable_selinux_bootloader \
selinux_state \
selinux_policytype \
securetty_root_login_console_only \
accounts_no_uid_except_zero \
no_empty_passwords \
accounts_password_minlen_login_defs \
accounts_maximum_age_login_defs \
accounts_password_warn_age_login_defs \
account_disable_post_pw_expiration \
accounts_password_pam_retry \
accounts_passwords_pam_faillock_deny \
accounts_password_pam_unix_remember \
set_password_hashing_algorithm_systemauth \
set_password_hashing_algorithm_logindefs \
accounts_umask_bashrc \
accounts_umask_cshrc \
accounts_umask_etc_profile \
accounts_umask_login_defs \
file_user_owner_grub_conf \
file_group_owner_grub_conf \
file_permissions_grub_conf \
bootloader_password \
disable_interactive_boot \
gconf_gnome_screensaver_idle_delay \
gconf_gnome_screensaver_idle_activation_enabled \
gconf_gnome_screensaver_lock_enabled \
gconf_gnome_screensaver_mode_blank \
set_system_login_banner \
gconf_gdm_enable_warning_gui_banner \
network_disable_zeroconf \
sysctl_net_ipv4_conf_default_send_redirects \
sysctl_net_ipv4_conf_all_send_redirects \
sysctl_net_ipv4_conf_all_accept_redirects \
sysctl_net_ipv4_conf_all_secure_redirects \
sysctl_net_ipv4_conf_all_log_martians \
sysctl_net_ipv4_conf_default_accept_source_route \
sysctl_net_ipv4_conf_default_accept_redirects \
sysctl_net_ipv4_conf_default_secure_redirects \
sysctl_net_ipv4_icmp_echo_ignore_broadcasts \
sysctl_net_ipv4_icmp_ignore_bogus_error_responses \
sysctl_net_ipv4_tcp_syncookies \
sysctl_net_ipv4_conf_all_rp_filter \
sysctl_net_ipv4_conf_default_rp_filter \
service_bluetooth_disabled \
kernel_module_bluetooth_disabled \
kernel_module_ipv6_option_disabled \
network_ipv6_disable_rpc \
sysctl_net_ipv6_conf_default_accept_ra \
sysctl_net_ipv6_conf_default_accept_redirects \
service_ip6tables_enabled \
service_iptables_enabled \
kernel_module_dccp_disabled \
kernel_module_sctp_disabled \
kernel_module_rds_disabled \
kernel_module_tipc_disabled \
package_rsyslog_installed \
service_rsyslog_enabled \
service_auditd_enabled \
bootloader_audit_argument \
audit_rules_time_adjtimex \
audit_rules_time_settimeofday \
audit_rules_time_stime \
audit_rules_time_clock_settime \
audit_rules_time_watch_localtime \
audit_rules_usergroup_modification \
audit_rules_networkconfig_modification \
audit_rules_mac_modification \
audit_rules_dac_modification_chmod \
audit_rules_dac_modification_chown \
audit_rules_dac_modification_fchmod \
audit_rules_dac_modification_fchmodat \
audit_rules_dac_modification_fchown \
audit_rules_dac_modification_fchownat \
audit_rules_dac_modification_fremovexattr \
audit_rules_dac_modification_fsetxattr \
audit_rules_dac_modification_lchown \
audit_rules_dac_modification_lremovexattr \
audit_rules_dac_modification_lsetxattr \
audit_rules_dac_modification_removexattr \
audit_rules_dac_modification_setxattr \
audit_rules_unsuccessful_file_modification \
audit_rules_privileged_commands \
audit_rules_media_export \
audit_rules_file_deletion_events \
audit_rules_sysadmin_actions \
audit_rules_kernel_module_loading \
audit_rules_immutable \
uninstall_xinetd \
uninstall_telnet_server \
package_rsh-server_removed \
uninstall_ypserv \
service_tftp_disabled \
uninstall_tftp-server \
service_kdump_disabled \
service_portreserve_disabled \
service_rhnsd_disabled \
service_crond_enabled \
service_atd_disabled \
sshd_allow_only_protocol2 \
sshd_set_idle_timeout \
sshd_set_keepalive \
sshd_disable_rhosts \
disable_host_auth \
sshd_disable_root_login \
sshd_disable_empty_passwords \
sshd_enable_warning_banner \
sshd_do_not_permit_user_env \
sshd_use_approved_ciphers \
disable_avahi \
disable_dhcp_server \
uninstall_dhcp_server \
service_ntpd_enabled \
ntpd_specify_remote_server \
package_sendmail_removed \
package_openldap-servers_removed \
service_nfslock_disabled \
service_rpcgssd_disabled \
service_rpcidmapd_disabled \
service_netfs_disabled \
service_rpcsvcgssd_disabled \
disable_dns_server \
uninstall_bind \
disable_vsftpd \
uninstall_vsftpd \
disable_httpd \
package_httpd_removed \
disable_dovecot \
package_dovecot_removed \
disable_smb_server \
require_smb_client_signing \
disable_squid \
uninstall_squid \
disable_snmpd"

##
# Custom rule list. Make your own! What could be more fun!
CUSTOM=""
